### ISSUE TITLE
Check pull requests for conflicts

### ISSUE THREAD

**Issue by knod** [jamestomasino/read_plugin#15]
If this is rude, I apologize. I don't have a lot of experience with pull requests, so I wasn't sure if the upstream gets a notice if there's a pull request waiting. Figured I might as well make sure.

**Comment by jamestomasino** [comment]
Hi @knod - for some reason I didn't get a notification. I've merged in your pull requests. The only one I'm unsure on is the centering of the text. RSVP research shows best speeds are achieved with the alignment point at 1/3rd of the word length. I'll test your version out and see how it goes.

**Comment by knod** [comment]
Ah, understood. Hmm, will have to think on that.

**Comment by jamestomasino** [comment]
I reverted the centered code to leave it focused on 1/3rd. That might be a good option to include as a choice for users in the menu. If there's a better method for adding multi-lingual support, RTL languages will certainly want to consider using the last third instead of the first. Centered is an easy option as well.
